export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'about': 'About us',
  'anonimous': 'Anonimous',
  'chest': 'Chest',
  'back': 'Back',
  'generate session': 'Generate fast session',
  'gym': 'Fitness center',
  'height': 'Height',
  'home': 'Home',
  'house': 'Home',
  'increase mass': 'Increase mass',
  'lose weight': 'Lose weight',
  'months': 'Months',
  'register': 'Register',
  'session in': 'Log in',
  'session out': 'Log out',
  'slogan': 'Wellness, Inspiration, Motivation',
  'target': 'Select your goal',
  'thigh - hip': 'Thigh - hip',
  'to tone': 'To tone',
  'today': 'What do you train today?',
  'training place': 'Where do you train?',
  'training time': 'How long have you been training?',
  'weight': 'Weight',
  'welcome': 'Welcome',
};
