export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
  'about': 'Nosotros',
  'anonimous': 'Anónimo',
  'chest': 'Pecho',
  'back': 'Espalda',
  'generate session': 'Generar sesión rápida',
  'gym': 'Gimnasio',
  'height': 'Estatura',
  'home': 'Inicio',
  'house': 'Casa',
  'increase mass': 'Incrementar masa',
  'lose weight': 'Perder peso',
  'months': 'Meses',
  'register': 'Registro',
  'session in': 'Entrar',
  'session out': 'Salir',
  'slogan': 'Bienestar, Inspiración, Motivación',
  'target': '¿Cuál es tu objetivo?',
  'thigh - hip': 'Muslo - cadera',
  'to tone': 'Tonificar',
  'today': '¿Qué entrenas hoy?',
  'training place': '¿Donde entrenas?',
  'training time': '¿Hace cuánto entrenas?',
  'weight': 'Peso',
  'welcome': 'Bienvenido',
};
